---
Name: mysite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'hydra'

SiteConfig:
  extensions:
   - CustomSiteConfig
DBField:
  extensions:
   - RichLinksExtension
LeftAndMain:
  extra_requirements_css:
   - 'mysite/css/custom.css'

ErrorPage:
  icon: "mysite/images/sitetree_images/error.png"
UserDefinedForm:
  icon: "mysite/images/sitetree_images/form.png"
  extensions:
   - UserDefinedFormExtension

SubmittedForm:
  extensions:
   - SubmittedFormExtension

Link:
  extensions:
   - LinkExtension
